### ISSUE TITLE
爬取5K分辨率超清唯美壁纸报错

### ISSUE THREAD

**Issue by KingBoyAndGirl** [shengqiangzhang/examples-of-web-crawlers#103]
```
壁纸类型：最新壁纸 1, 最热壁纸 2, 女生壁纸 3, 星空壁纸 4
请输入编号以便选择5K超清壁纸类型：1
请输入要下载的5K超清壁纸的数量：1
正在下载5K超清壁纸，请稍等……
Traceback (most recent call last):
  File "D:/Project/PythonProject/crawl/crawler_5K_wallpaper/crawler_5K_wallpaper.py", line 109, in <module>
    crawler_photo(int(wall_paper_id), int(wall_paper_count))
  File "D:/Project/PythonProject/crawl/crawler_5K_wallpaper/crawler_5K_wallpaper.py", line 51, in crawler_photo
    photo_data = loads(respond.content)
  File "f:\python\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "f:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "f:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

```

**Comment by wight911** [comment]
I guess it is because the service endpoint has been changed or is not valid for now. 
i.e. for example, https://service.paper.meiyuan.in/api/v2/columns/flow/5c68ffb9463b7fbfe72b0db0?page=1&per_page=20 
is not valid.

**Comment by shengqiangzhang** [comment]
@KingBoyAndGirl 已修复，详见[https://github.com/shengqiangzhang/examples-of-web-crawlers/commit/5b986829fefb09d27eff4b78be0dc8dc33d2518e](https://github.com/shengqiangzhang/examples-of-web-crawlers/commit/5b986829fefb09d27eff4b78be0dc8dc33d2518e)

@wight911 是的，现在已经改成动态模式，壁纸id自动更新，详见[https://github.com/shengqiangzhang/examples-of-web-crawlers/commit/5b986829fefb09d27eff4b78be0dc8dc33d2518e](https://github.com/shengqiangzhang/examples-of-web-crawlers/commit/5b986829fefb09d27eff4b78be0dc8dc33d2518e)
