### ISSUE TITLE
我是是个超级白的小白，你那个微信书籍笔记导出的，我看不懂，你可以留个联系方式吗，活着，告诉我用什么都是需要什么工具，和步骤吗？

### ISSUE THREAD

**Issue by 501830865** [shengqiangzhang/examples-of-web-crawlers#104]
我真的很需要，跪求

**Comment by shengqiangzhang** [comment]
> 我真的很需要，跪求

@501830865 有Python的经验吗？如果没有的话，可以联系我提供一个直接可以运行的程序。

**Comment by wushuiyin004** [comment]
> > 我真的很需要，跪求
> 
> @501830865有 Python 的经验吗？如果没有的话，可以联系我提供一个可以直接运行的程序。

大佬 求一份直接运行的程序 已发博客下的77gmail邮件
