### ISSUE TITLE
微信读书，登录成功后，就报错。

### ISSUE THREAD

**Issue by barnett2010** [shengqiangzhang/examples-of-web-crawlers#106]
![image](https://user-images.githubusercontent.com/8305408/124627496-22b5ad80-de6f-11eb-9071-9010bb23beea.png)
如图
登录微信读书成功!
用户id:123456
Traceback (most recent call last):
  File "pyqt_gui.py", line 147, in <module>
    books = get_bookshelf(USER_VID, HEADERS) # 获取书架上的书籍
  File "C:\Users\xnj\Desktop\weread\wereader.py", line 156, in get_bookshelf
    b = Book(book['bookId'], book['title'], book['author'], book['cover'], book[
'intro'], book['category'])
KeyError: 'intro'

**Comment by barnett2010** [comment]
是网页改版影响了吗

**Comment by wxweven** [comment]
+1 同样报错了，有什么解法办法吗？

**Comment by SeikoSrp** [comment]
+1,同样报错

**Comment by panwanpeng** [comment]
Received. Many thanks!
I will read it quickly .

**Comment by YrracOwl** [comment]
微信网页版现在返回的data里面没有intro和category了，手动删除所有的, book['intro'], book['category']，以及在pyqt_gui.py里面的中文的 ["ID", "标题", "作者", "封面"]这个list后面的就可以了

**Comment by panwanpeng** [comment]
Received. Many thanks!
I will read it quickly .
