### ISSUE TITLE
直接运行报错，修改了浏览器用户代理User-Agent和图片下载URL，还是有json解析错误。

### ISSUE THREAD

**Issue by githubmzgg** [shengqiangzhang/examples-of-web-crawlers#107]
![image](https://user-images.githubusercontent.com/38745620/159414542-579fd7f3-c8d4-47dd-8b09-21ae08aef555.png)

感觉这个爬虫案例适用性太窄，真的要run起来，需要根据自己的URL解析JSON

**Comment by githubmzgg** [comment]
忘了说，这是指爬取图片壁纸的那个案例。

我用的是Windows系统，在Chrome浏览器打开下载地址提示500错误，自己随便换了个图片地址

**Comment by shengqiangzhang** [comment]
@githubmzgg 你好，你这张截图可能是从旧版的软件截图的吧？现在程序已经更新了。并且，更新后的程序理论上可以永久使用，URL解析是改成动态的了。

麻烦你重新下载下源代码运行一下，目前没有发布成品。
