### ISSUE TITLE
mismatched tag: line 63, column 4

### ISSUE THREAD

**Issue by KeAuy** [shengqiangzhang/examples-of-web-crawlers#108]
![image](https://user-images.githubusercontent.com/93756508/161386941-07c08004-d224-4487-b741-022208363414.png)

**Comment by shengqiangzhang** [comment]
@KeAuy 该程序依赖微信网页版API，请手动登录https://wx.qq.com/，检查是否可以登录。如果不行的话，本程序也是用不了的。
