### ISSUE TITLE
豆瓣电影GUI界面

### ISSUE THREAD

**Issue by qian-yu-a** [shengqiangzhang/examples-of-web-crawlers#109]
getMovieInRankingList.py中报错：
在 'ssl.pyi' 中找不到引用 '_create_unverified_context'

GUI界面可以正常打开，但搜索时会报错：Python[6027:7986884] Warning: Expected min height of view: (<NSButton: 0x7f945f0bbb50>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.

**Comment by shengqiangzhang** [comment]
@qian-yu-a 请提供以下报错截图和python版本

**Comment by qian-yu-a** [comment]
版本：python3.8    前面的问题已经解决了（并未进行其他操作😂），目前的问题：选择影片点击初始化后会出现以下如图错误，但页面正常返回搜索内容，经过尝试发现windows比mac出现的更频繁；IMDB评分一直处于加载中；搜索后的云盘及影视链接大部分已失效。
win
![win](https://user-images.githubusercontent.com/63407335/165349380-6788602a-9e2a-4594-8b50-78de9ff3b43b.png)
mac
<img width="957" alt="mac" src="https://user-images.githubusercontent.com/63407335/165349419-dcbcede4-6413-43b9-b102-278cb8bbcb6a.png">

**Comment by qian-yu-a** [comment]
@shengqiangzhang  版本：python3.8。前面的问题已经解决了（未进行其他操作😂），目前的问题：点击初始化后会出现如下图错误，但页面正常显示返回内容，经测试发现windows比mac更频繁； IMDB评分一直处于加载中；搜索后显示的云盘及影视播放地址大部分已失效。
<img width="939" alt="mac" src="https://user-images.githubusercontent.com/63407335/165352866-6d1ee05c-8c5b-4984-b599-8faa8c2ca628.png">
![win](https://user-images.githubusercontent.com/63407335/165352928-5c3f5eff-ece4-4e93-9997-14d7461289f6.png)

**Comment by shengqiangzhang** [comment]
@qian-yu-a 收到，明日检查一下～

**Comment by qian-yu-a** [comment]
深夜打扰，抱歉！

**Comment by shengqiangzhang** [comment]
@qian-yu-a 我这边测试了下，基本没问题。有可能是IMDB网站被墙了。
你自行访问一下[https://www.imdb.com/](https://www.imdb.com/)，如果访问不了，说明你所在的地区屏蔽了IMDB。

**Comment by shengqiangzhang** [comment]
@qian-yu-a 
1. 我这边测试了，没有出现异常的情况。我猜测可能是你所在的地区无法访问IMDB。你自行访问一下[https://www.imdb.com/](https://www.imdb.com/)，如果访问不了，说明你所在的地区屏蔽了IMDB。
2. 搜索后显示的云盘及影视播放地址大部分已失效。这个没有办法，目前大部分确实失效了。
