### ISSUE TITLE
> 您好，我跳出滑动验证码的时候老是过不去页面上显示“哎呀，出错了，点击刷新再来一次(error:NgaRgk)”,然后程序显示‘selenium.common.exceptions.TimeoutException: Message:’，请问大佬该怎么破。。

### ISSUE THREAD

**Issue by wangjf1993** [shengqiangzhang/examples-of-web-crawlers#14]
> 您好，我跳出滑动验证码的时候老是过不去页面上显示“哎呀，出错了，点击刷新再来一次(error:NgaRgk)”,然后程序显示‘selenium.common.exceptions.TimeoutException: Message:’，请问大佬该怎么破。。

我这边测试目前是正常的哦，如果不正常的话，你手动登录网页滑动一次，下次一般就不会提示了。

_Originally posted by @shengqiangzhang in https://github.com/shengqiangzhang/examples-of-web-crawlers/issues/4#issuecomment-474821621_

楼主，为什么我这边只要是用了selenium打开网页，手动登录都无法登录的。即便添加了开发者模式、、、、这个问题已经困扰我好久了。

**Comment by Lawlighty** [comment]
您好,使用 淘宝账号密码登录的话会出现滑块,手工滑动也通不过验证 OrZ ,要怎么做?

**Comment by JOHNYXUU** [comment]
我也困扰了很久，感觉是tmall这边的反爬虫措施更加完善了

**Comment by Daoling** [comment]
> 您好，我跳出滑动验证码的时候老是过不去页面上显示“哎呀，出错了，点击刷新再来一次(error:NgaRgk)”,然后程序显示‘selenium.common.exceptions.TimeoutException: Message:’，请问大佬该怎么破。。
> 
> 我这边测试目前是正常的哦，如果不正常的话，你手动登录网页滑动一次，下次一般就不会提示了。
> Originally posted by @shengqiangzhang in #4 (comment)
> 楼主，为什么我这边只要是用了selenium打开网页，手动登录都无法登录的。即便添加了开发者模式、、、、这个问题已经困扰我好久了。

遇到了同样的问题，请问解决了么？

**Comment by wuyezhao** [comment]
我也遇到了，请问有什么办法操作吗？

**Comment by panwanpeng** [comment]
Received. Many thanks!
I will read it quickly .
