### ISSUE TITLE
微信一键生成个人报告，卡在人脸识别不动了，win7系统

### ISSUE THREAD

**Issue by wushi565** [shengqiangzhang/examples-of-web-crawlers#18]
微信卡在人脸识别第一个不动了，有很长时间。

**Comment by shengqiangzhang** [comment]
> 微信卡在人脸识别第一个不动了，有很长时间。

麻烦提供下截图。

**Comment by wushi565** [comment]
> > 微信卡在人脸识别第一个不动了，有很长时间。
> 
> 麻烦提供下截图。

![2019-04-23_170839](https://user-images.githubusercontent.com/35413073/56568843-6901f780-65ea-11e9-9638-4cc93abad6f2.png)

**Comment by wushi565** [comment]
> > > 微信卡在人脸识别第一个不动了，有很长时间。
> > 
> > 
> > 麻烦提供下截图。
> 
> ![2019-04-23_170839](https://user-images.githubusercontent.com/35413073/56568843-6901f780-65ea-11e9-9638-4cc93abad6f2.png)

你好，有2个多小时一直是在这个界面，并且前面也重启了好几次，都是在这个界面卡住，不动了

**Comment by shengqiangzhang** [comment]
> > > > 微信卡在人脸识别第一个不动了，有很长时间。
> > > 
> > > 
> > > 麻烦提供下截图。
> > 
> > 
> > ![2019-04-23_170839](https://user-images.githubusercontent.com/35413073/56568843-6901f780-65ea-11e9-9638-4cc93abad6f2.png)
> 
> 你好，有2个多小时一直是在这个界面，并且前面也重启了好几次，都是在这个界面卡住，不动了

你在当前目录下添加一个图片，文件名为lena.png
然后新建一个py文件，添加以下代码，看看有没有反应，以便测试你安装的opencv库是否正常
```
import cv2
image = cv2.imread("lena.png")
cv2.imshow("Image",image)
cv2.waitKey(0)
```

**Comment by shengqiangzhang** [comment]
> > > > 微信卡在人脸识别第一个不动了，有很长时间。
> > > 
> > > 
> > > 麻烦提供下截图。
> > 
> > 
> > ![2019-04-23_170839](https://user-images.githubusercontent.com/35413073/56568843-6901f780-65ea-11e9-9638-4cc93abad6f2.png)
> 
> 你好，有2个多小时一直是在这个界面，并且前面也重启了好几次，都是在这个界面卡住，不动了

目测是版本问题
