### ISSUE TITLE
使用

### ISSUE THREAD

**Issue by Peng-Xia** [shengqiangzhang/examples-of-web-crawlers#2]
使用手册能不能再详细点，如何在Linux运行

**Comment by shengqiangzhang** [comment]
> 使用手册能不能再详细点，如何在Linux运行

你好，想要看哪个项目，直接点那个文件夹，里面有详细的说明呢。在Linux和windows和macosx下的运行方式都是一样的。

可以在命令行直接输入 python 文件名.py运行
