### ISSUE TITLE
【问题反馈】微信扫码出现无法识别的二维码

### ISSUE THREAD

**Issue by weijiawei** [shengqiangzhang/examples-of-web-crawlers#20]
![image](https://user-images.githubusercontent.com/15064041/56625838-a78ec500-6671-11e9-9b96-9684296dc345.png)

**Comment by weijiawei** [comment]
IOS设备似乎无法识别二维码

**Comment by shengqiangzhang** [comment]
> IOS设备似乎无法识别二维码

升级微信版本就好了

**Comment by weijiawei** [comment]
> > IOS设备似乎无法识别二维码
> 
> 升级微信版本就好了

不是呀，我测试的IOS微信是最新版本的。

**Comment by weijiawei** [comment]
> > > IOS设备似乎无法识别二维码
> > 
> > 
> > 升级微信版本就好了
> 
> 不是呀，我测试的IOS微信是最新版本的。

https://ws3.sinaimg.cn/large/005BYqpgly1g2enelb88gj30ku112jub.jpg
