### ISSUE TITLE
总页数的css__selector

### ISSUE THREAD

**Issue by JOHNYXUU** [shengqiangzhang/examples-of-web-crawlers#21]
#content > div > div.ui-page > div > b.ui-page-skip > form > input[type="hidden"]:nth-child(7)
和你当时写的不一样了，现在还有什么方法可以破吗

**Comment by shengqiangzhang** [comment]
理论上是一样的，如果不一样你可以自己改。用.和#就可以了，.是class名,#是ID名，你最后一条应该是不对的
```
 input[type="hidden"]:nth-child(7)
```

**Comment by JOHNYXUU** [comment]
可是我是从网页上直接copy selector下来的啊。。
