### ISSUE TITLE
大神好,pycharts版本问题？

### ISSUE THREAD

**Issue by Jasonandy** [shengqiangzhang/examples-of-web-crawlers#28]
![image](https://user-images.githubusercontent.com/12879147/58392152-2a3ce280-806b-11e9-9b0e-c9210da3bd13.png)

**Comment by Jasonandy** [comment]
![image](https://user-images.githubusercontent.com/12879147/58392319-fb733c00-806b-11e9-974b-d9cf0ed8549d.png)

**Comment by Jasonandy** [comment]
降级为0.5X版本 问题解决 谢谢大神开源

**Comment by daofeng2015** [comment]
我tm也遇到了。。。。作者没说
