### ISSUE TITLE
可执行文件闪退

### ISSUE THREAD

**Issue by likeyun** [shengqiangzhang/examples-of-web-crawlers#29]
可执行文件闪退

**Comment by shengqiangzhang** [comment]
@likeyun 
具体是哪个

**Comment by xsohydra** [comment]
我的闪退是因为找不到chromedriver_win32_74.0.3729.6.exe
把75的chromedriver重命名成chromedriver_win32_74.0.3729.6.exe然后和可执行文件放一个目录就好了。

**Comment by tectal** [comment]
我也是，成品文件夹里面的exe文件，运行闪退

**Comment by Axinyp** [comment]
那个守护女友项目出问题了，索引超出界限
Traceback (most recent call last):
  File "say_to_lady.py", line 272, in <module>
IndexError: list index out of range
[1560] Failed to execute script say_to_lady

**Comment by Zpolar** [comment]
同样闪退
![360截图1661071686102118](https://user-images.githubusercontent.com/52811944/61105123-863cb880-a4ab-11e9-8ad2-5728b1a62199.png)
