### ISSUE TITLE
可以做一个微信书(心书)的PDF导出吗？出书啦的有个限制，个人分组设置成私密的看不到。谢谢！

### ISSUE THREAD

**Issue by xsohydra** [shengqiangzhang/examples-of-web-crawlers#32]
我也想自己修改代码做一个，但心书的页面直接调用系统打印PDF图片全部是空白（非懒加载），看了一下源码好像图片全部是调用的CSS，不知道应该怎么处理。

**Comment by shengqiangzhang** [comment]
@xsohydra 暂时没有做，你可以根据自己的要求改写代码。
