### ISSUE TITLE
天猫爬虫的登录验证问题

### ISSUE THREAD

**Issue by Focke-Wulf** [shengqiangzhang/examples-of-web-crawlers#38]
天猫 做滑块验证的时候，直接使用move_by_offset 函数 直接一拖到底 貌似会被检测到非人工
使用轨迹 循环拖动 会很慢，也会被检测到异常，这个问题该怎么办呢

**Comment by shengqiangzhang** [comment]
@Focke-Wulf 此方法已失效，目前几乎没有任何办法。

**Comment by lsydd** [comment]
同遇到这个问题。。。

**Comment by lsydd** [comment]
> 天猫 做滑块验证的时候，直接使用move_by_offset 函数 直接一拖到底 貌似会被检测到非人工
> 使用轨迹 循环拖动 会很慢，也会被检测到异常，这个问题该怎么办呢
同遇到这个问题，请问您想到解决方案了吗？

**Comment by lsydd** [comment]
> 天猫 做滑块验证的时候，直接使用move_by_offset 函数 直接一拖到底 貌似会被检测到非人工
> 使用轨迹 循环拖动 会很慢，也会被检测到异常，这个问题该怎么办呢

同遇到这个问题，请问您想到解决方案了吗？

**Comment by lsydd** [comment]
> 天猫 做滑块验证的时候，直接使用move_by_offset 函数 直接一拖到底 貌似会被检测到非人工
> 使用轨迹 循环拖动 会很慢，也会被检测到异常，这个问题该怎么办呢

@Focke-Wulf 同遇到这个问题，请问您想到解决方案了吗？
