### ISSUE TITLE
淘宝 滑动验证码过不去

### ISSUE THREAD

**Issue by luvm** [shengqiangzhang/examples-of-web-crawlers#4]
您好，我跳出滑动验证码的时候老是过不去页面上显示“哎呀，出错了，点击刷新再来一次(error:NgaRgk)”,然后程序显示‘selenium.common.exceptions.TimeoutException: Message:’，请问大佬该怎么破。。

**Comment by shengqiangzhang** [comment]
> 您好，我跳出滑动验证码的时候老是过不去页面上显示“哎呀，出错了，点击刷新再来一次(error:NgaRgk)”,然后程序显示‘selenium.common.exceptions.TimeoutException: Message:’，请问大佬该怎么破。。

我这边测试目前是正常的哦，如果不正常的话，你手动登录网页滑动一次，下次一般就不会提示了。

**Comment by triangle959** [comment]
我也是出现这个情况，爬取到了数据，但是出现security-X5页面，然后滑块验证一直不通过。我在滑块验证后面加上self.browser.back()，让浏览器返回之前页面，然后继续输页码来爬取。

**Comment by lwshanbd** [comment]
您好，我也出现了这种情况，经过分析是因为selenium的滑动速度过快，请问有什么解决方案么
