### ISSUE TITLE
微信的发消息的功能报KeyError: 'pass_ticket'，是不是账号被封禁了？wxpy还能用吗？

### ISSUE THREAD

**Issue by CLAY-X** [shengqiangzhang/examples-of-web-crawlers#5]

**Comment by shengqiangzhang** [comment]
这个账号是新注册的小号或者常年未登录的老号，请换一个正常使用的号码登陆。打开https://wx.qq.com/?lang=zh_CN这里登录，看看具体提示的信息是什么。

**Comment by shengqiangzhang** [comment]
> _No description provided._

这个账号是新注册的小号或者常年未登录的老号，请换一个正常使用的号码登陆。打开[https://wx.qq.com/?lang=zh_CN](https://wx.qq.com/?lang=zh_CN)这里登录，看看具体提示的信息是什么。

**Comment by CLAY-X** [comment]
<error><ret>1203</ret><message>为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>

**Comment by shengqiangzhang** [comment]
> 1203为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com Mac微信下载地址：https://mac.weixin.qq.com

换常用微信号
