### ISSUE TITLE
运行python generate_wx_data.py 报错

### ISSUE THREAD

**Issue by mark988** [shengqiangzhang/examples-of-web-crawlers#59]
![image](https://user-images.githubusercontent.com/22902512/66819445-944e1980-ef71-11e9-854d-f496530e2566.png)

**Comment by youngxkk** [comment]
看倒数第三行，没有 import wxpy

**Comment by youngxkk** [comment]
试试 pip install wxpy

**Comment by shengqiangzhang** [comment]
执行 `pip install wxpy`
