### ISSUE TITLE
微博登录要验证码

### ISSUE THREAD

**Issue by hahaLiShuning** [shengqiangzhang/examples-of-web-crawlers#6]

**Comment by shengqiangzhang** [comment]
> No description provided.

请用常用账号登录

**Comment by Ko8e-24** [comment]
我也是这个情况，每次都需要输入验证码，使用的就是常用账户

**Comment by Ko8e-24** [comment]
老哥还有其他解决方法吗 @shengqiangzhang

**Comment by shengqiangzhang** [comment]
> 老哥还有其他解决方法吗 @shengqiangzhang

淘宝天猫目前来说，爬取数据难度很大了。你先手动登录微博官网，还有手动通过微博登录淘宝或者天猫，多弄几次，运气好的话就无需验证码吗，运气差的话可能要等1-2天。

使用get/post方式目前来说很难搞定，使用selenium会有频率限制，这个就看你的经验了

**Comment by Ko8e-24** [comment]
好的，谢啦 @shengqiangzhang
