### ISSUE TITLE
分析数据的时候报错了

### ISSUE THREAD

**Issue by mark988** [shengqiangzhang/examples-of-web-crawlers#60]
![image](https://user-images.githubusercontent.com/22902512/66823840-9d42e900-ef79-11e9-8747-c0ecdc640964.png)

**Comment by zhihuitang** [comment]
已修复：https://github.com/shengqiangzhang/examples-of-web-crawlers/pull/68

**Comment by shengqiangzhang** [comment]
已由 @zhihuitang 修复。
