### ISSUE TITLE
是否可以直接登陆淘宝？

### ISSUE THREAD

**Issue by whisper-a** [shengqiangzhang/examples-of-web-crawlers#64]
请问为什么要通过微博跳转登陆呢，用taobao.com直接登陆有哪些问题？

**Comment by shengqiangzhang** [comment]
@whisper-a 

淘宝检测十分严格，采用`selenium`直接在淘宝进行登录几乎不可行，所以通过授权中心间接登录。

**Comment by whisper-a** [comment]
get it, thank you for your response.



在 2019-12-24 01:38:53，"Shengqiang Zhang" <notifications@github.com> 写道：

@whisper-a

淘宝检测十分严格，采用selenium直接在淘宝进行登录几乎不可行，所以通过授权中心间接登录。

**Comment by panwanpeng** [comment]
niubility.
