### ISSUE TITLE
等待加载全部商品数据为什么不是presence_of_all_elements_located？

### ISSUE THREAD

**Issue by zaoyubo** [shengqiangzhang/examples-of-web-crawlers#65]
https://github.com/shengqiangzhang/examples-of-web-crawlers/blob/5dfe4f5f6e4816213cddafe80e9b0fc2a50bc081/2.%E5%A4%A9%E7%8C%AB%E5%95%86%E5%93%81%E6%95%B0%E6%8D%AE%E7%88%AC%E8%99%AB(%E5%B7%B2%E6%A8%A1%E6%8B%9F%E7%99%BB%E5%BD%95)/tmall_crawler.py#L151

**Comment by shengqiangzhang** [comment]
@zaoyubo 

用的确实是`EC.presence_of_element_located`
而`self.wait.until`是直到元素出现的意思。
