### ISSUE TITLE
豆瓣GUI打开一片空白呀

### ISSUE THREAD

**Issue by ladychili** [shengqiangzhang/examples-of-web-crawlers#7]
![image](https://user-images.githubusercontent.com/27876613/55282634-e6b24a80-533f-11e9-8b7b-146941d5ec27.png)

如图。

**Comment by ladychili** [comment]
而且= = 怎么还有广告

**Comment by shengqiangzhang** [comment]
> 而且= = 怎么还有广告

现在解决了吗，这只是一个基本的python tkinter例子，应该不会存在空白的情况，我这边测试了好几个系统都正常呢

**Comment by ladychili** [comment]
![image](https://user-images.githubusercontent.com/27876613/55353535-716b8480-54bb-11e9-9a33-8c6af4f5ea2c.png)

是我用的方法不对吗？

**Comment by shengqiangzhang** [comment]
> ![image](https://user-images.githubusercontent.com/27876613/55353535-716b8480-54bb-11e9-9a33-8c6af4f5ea2c.png)
> 
> 是我用的方法不对吗？

退出git状态，或者关闭terminal，重新打开terminal，cd到指定文件夹后，执行python main.py
![WX20190402-120433](https://user-images.githubusercontent.com/28225826/55375698-ba651c80-553f-11e9-8904-5280d5b9159f.png)

**Comment by shengqiangzhang** [comment]
![111](https://user-images.githubusercontent.com/28225826/55375759-e97b8e00-553f-11e9-82ed-f14f87b4923e.png)

**Comment by ladychili** [comment]
什么叫退出git状态？ 只要cd到那个目录下就肯定会显示git状态啊。。
而且我是执行的 main.py啊 = =

**Comment by shengqiangzhang** [comment]
> 什么叫退出git状态？ 只要cd到那个目录下就肯定会显示git状态啊。。
> 而且我是执行的 main.py啊 = =

仔细看了一下，好像你的操作没有问题。你试试赋予主文件夹读写执行权限试试，命令如下：
`sudo chmod -R 777 examples-of-web-crawlers`

**Comment by ladychili** [comment]
![image](https://user-images.githubusercontent.com/27876613/55394113-74f02180-5536-11e9-8e81-6579b4531cb8.png)

还是一样..

**Comment by shengqiangzhang** [comment]
> ![image](https://user-images.githubusercontent.com/27876613/55394113-74f02180-5536-11e9-8e81-6579b4531cb8.png)
> 
> 还是一样..

你可以换一个系统或者PC或者联系你同学，看看能够运行起来吗？这样能够更快地排除问题。

**Comment by ladychili** [comment]
> 你可以使用pycharm运行试试，或者换一个系统或者PC或者联系你同学，看看能够运行起来吗？这样能够更快地排除问题。

已解决。是我的conda环境有问题，之前给弄乱了。本地python 3.6.2 可以正常运行。
