### ISSUE TITLE
为什么下载速度这么慢？

### ISSUE THREAD

**Issue by tienyeung** [shengqiangzhang/examples-of-web-crawlers#72]
非常佩服您的代码，无奈下载实在太慢，专门来抱怨一下，哈哈

**Comment by shengqiangzhang** [comment]
@tienyeung 

你好，
        在readme.md文件中的末位置有提供码云镜像仓库，方便没有使用代理上网的用户下载。
        镜像仓库地址：[https://gitee.com/shengqiangzhang/examples-of-web-crawlers](https://gitee.com/shengqiangzhang/examples-of-web-crawlers)

![image](https://user-images.githubusercontent.com/28225826/71357954-403f6100-25c2-11ea-8914-2f1165d79911.png)
