### ISSUE TITLE
克隆不下来，zip下载不了，太卡

### ISSUE THREAD

**Issue by hanlonghxp** [shengqiangzhang/examples-of-web-crawlers#82]
克隆不下来，zip下载不了，太卡
![image](https://user-images.githubusercontent.com/12080501/79034564-7fcd9f80-7be9-11ea-8463-fccf53fe0d93.png)

**Comment by shengqiangzhang** [comment]
## 如何下载

本仓库大小为<a href="https://github.com/shengqiangzhang/examples-of-web-crawlers"><img src="https://img.shields.io/github/repo-size/shengqiangzhang/examples-of-web-crawlers"></a>, 为提高下载速度, 建议使用代理服务器下载。

<br />

没有或不懂如何设置代理服务器的![chinese_flag](./chinese_flag.png)**中国用户**, 请跳转至本仓库同步镜像[码云Gitee](https://gitee.com/shengqiangzhang/examples-of-web-crawlers)进行下载, 以便获得较快的下载速度。
