### ISSUE TITLE
wxpy是否还能用呢

### ISSUE THREAD

**Issue by woodyxiong** [shengqiangzhang/examples-of-web-crawlers#84]
如题

**Comment by shengqiangzhang** [comment]
@woodyxiong wxpy可以用，wxpy基于微信网页版，不过现在部分新的微信号被禁止登录微信网页版了，要验证你的微信账号是否能够登录，请打开[https://wx.qq.com/](https://wx.qq.com/)扫码测试。如果无法登录，那么wxpy就不可以用。
