### ISSUE TITLE
微信登录，隔一段时间会timeout，需要定时扫描二维码登录，好麻烦

### ISSUE THREAD

**Issue by xiewendan** [shengqiangzhang/examples-of-web-crawlers#87]

**Comment by shengqiangzhang** [comment]
@xiewendan 
请具体描述一下？并截图。

**Comment by xiewendan** [comment]
大致是这样，我使用
wxpy这个库，
from wxpy import *
bot = Bot(cache_path = True)
会弹出二维码扫描登录，之后，隔了一个晚上，貌似 直接logout了，这样，我没办法一直发送微信消息，还得重新扫码登录，比较麻烦，不知道您有什么建议？

**Comment by shengqiangzhang** [comment]
可以加一个线程，每10分钟发一次消息，这样就不会掉线了。





------------------ 原始邮件 ------------------
发件人: xiewendan <notifications@github.com&gt;
发送时间: 2020年4月21日 13:08
收件人: shengqiangzhang/examples-of-web-crawlers <examples-of-web-crawlers@noreply.github.com&gt;
抄送: Shengqiang Zhang <sqzhang77@gmail.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[shengqiangzhang/examples-of-web-crawlers] 微信登录，隔一段时间会timeout，需要定时扫描二维码登录，好麻烦 (#87)

**Comment by xiewendan** [comment]
ok，我试一试，谢谢哈
