### ISSUE TITLE
淘宝模拟登录-第一步的微博登录CSS定位貌似不正确

### ISSUE THREAD

**Issue by vonreuental** [shengqiangzhang/examples-of-web-crawlers#89]
![image](https://user-images.githubusercontent.com/59676006/80298734-f52c9900-87c1-11ea-8eb2-6e2043d60fe7.png)

请问这里是不是因为淘宝改过了，看css样式定位的代码对象好像是忘记密码
我们是不是应该点击 微博登录
        password_login = self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, 'a.weibo-login')))

**Comment by shengqiangzhang** [comment]
@vonreuental 
你可以看代码的注释，首先是等待“使用密码登录”这个元素出现，经过CSS审查元素发现确实是.forget-pwd，确实不是代表忘记密码的意思。

然后出现“使用密码登录”这个元素后，再选择“微博登录”。
