### ISSUE TITLE
微信读书笔记不全

### ISSUE THREAD

**Issue by Higurashi-kagome** [shengqiangzhang/examples-of-web-crawlers#91]

**Comment by CareLaden** [comment]
确实不全。阅读超过 200+ 书籍，其中有笔记得至少 150+，但实际导出得笔记字典只有 30 个项目。是不是因为一些下架书籍无法导出？但应用内查看笔记是可以看到得，只是原文无法获取和定位。

**Comment by CareLaden** [comment]
![image](https://user-images.githubusercontent.com/18063251/95155615-1fe63900-07c7-11eb-9fc4-a60abf853fdc.png)

**Comment by liuhao326** [comment]
从 pyqt_gui.py, line 162,163：
```
# 获取书架上的每本书籍的笔记
    for index, book in enumerate(books_finish_read):
         ...
```
可知，程序将只会帮助导出已读完书籍的笔记，未读完书本中的笔记将不会导出，这样设计是合理的。
