### ISSUE TITLE
建议：支持导出微信读书“已购内容”

### ISSUE THREAD

**Issue by f2sky** [shengqiangzhang/examples-of-web-crawlers#92]
![IMG_9617](https://user-images.githubusercontent.com/8769077/81459717-e4255400-91d3-11ea-819e-b9508b4ec707.jpg)
![IMG_9618](https://user-images.githubusercontent.com/8769077/81459721-e8ea0800-91d3-11ea-9584-0e037924c103.jpg)

----------------
已购书籍列表路径：我——账户——已购内容
已购书籍清单内容：
1、“已购内容”中的书籍列表；
2、每本书包含（都可以在版权信息中获取）：
- 书名
- 作者
- 出版社
- ISBN

以上，感谢。

**Comment by shengqiangzhang** [comment]
目前没有在更新了，你可以提交一下PR
