### ISSUE TITLE
微信现在无法登陆网页版怎么办呢

### ISSUE THREAD

**Issue by ArlanCooper** [shengqiangzhang/examples-of-web-crawlers#94]
现在好像是微信都不能登陆网页版的了，这些微信接口没办法调用了，请问有办法解决吗

**Comment by panwanpeng** [comment]
这简单，买一个能登陆网页版的微信啊

**Comment by nevlate** [comment]
> 这简单，买一个能登陆网页版的微信啊
哪里有卖呢

**Comment by ZhangJiaBa** [comment]
求助 登不上去咋办

**Comment by Geralt-x** [comment]
运行项目弹出二维码，扫码登录然后直接报错，wxpy接口被封死了，搞不了咯,

**Comment by WeikoOrz** [comment]
login.py 212行的pass_ticket出现keyerror

**Comment by 18387095384** [comment]
我也好奇现在怎么登录微信网页版

**Comment by huaDemo** [comment]
一样的情况，扫码后报错，有什么替代方案吗
