### ISSUE TITLE
微信读书笔记导出为空

### ISSUE THREAD

**Issue by lovecn** [shengqiangzhang/examples-of-web-crawlers#95]
运行没问题，但获取不到笔记了，我的笔记目前下是空的。

**Comment by liuhao326** [comment]
这可能是因为你没有将那些书读完。程序将只会帮助导出已读完书籍的笔记，一本书如果没有读完，即使其中有标注也不会被导出。

**Comment by CareLaden** [comment]
> 这可能是因为你没有将那些书读完。程序将只会帮助导出已读完书籍的笔记，一本书如果没有读完，即使其中有标注也不会被导出。

但是即便读完，也有 很多书籍没法导出，甚至直接都没显示

**Comment by liuhao326** [comment]
我没有遇到这个问题。
有时候一本书差不多读完了但实际上微信读书不会记录为读完，你现在的微信读书中是否有正确的已读书籍记录？如图：
![image](https://user-images.githubusercontent.com/51501079/95161153-fcc28600-07d4-11eb-83f8-29d6692ea19b.png)
另外，“没显示”可能是因为已读完的书籍中并没有标注内容，没标注自然就不会有内容。 @CareLaden

**Comment by CareLaden** [comment]
> 我没有遇到这个问题。
> 有时候一本书差不多读完了但实际上微信读书不会记录为读完，你现在的微信读书中是否有正确的已读书籍记录？如图：
> ![image](https://user-images.githubusercontent.com/51501079/95161153-fcc28600-07d4-11eb-83f8-29d6692ea19b.png)
> 另外，“没显示”可能是因为已读完的书籍中并没有标注内容，没标注自然就不会有内容。 @CareLaden

确定是读完的，例如《美国读者》这本书阅读记录显示读完，个人主页显示读完，且打开该书籍具体的读者信息也显示我已读完。
![image](https://user-images.githubusercontent.com/18063251/95163200-ed920700-07d9-11eb-82f7-67e6a8370b63.png)
![image](https://user-images.githubusercontent.com/18063251/95163208-f256bb00-07d9-11eb-9f7c-14d3da6554a1.png)
![image](https://user-images.githubusercontent.com/18063251/95163210-f551ab80-07d9-11eb-8788-9590113d786a.png)

**Comment by liuhao326** [comment]
导出的 Excel 表格中有该书吗？

**Comment by CareLaden** [comment]
> 导出的 Excel 表格中有该书吗？

有的，初步判断是 'createTime' 有问题，因为我一开始用的是打包好的程序去执行，出现问题后我试过自己跑原始代码也是出现同样的报错，报错的时期都一样。看开发者怎么解决了
![image](https://user-images.githubusercontent.com/18063251/95164378-73af4d00-07dc-11eb-95ec-fe46c511f842.png)

**Comment by liuhao326** [comment]
我注意到这一行代码似乎并没有用处，你可以尝试注释掉这一行代码再试。 @CareLaden

**Comment by CareLaden** [comment]
测试过，不行，报了一大堆错误。
![image](https://user-images.githubusercontent.com/18063251/95164862-6b0b4680-07dd-11eb-9908-8380c2e6ed46.png)
我用的 PyQt5 版本低了点，不想升级太麻烦。

**Comment by liuhao326** [comment]
哦，如果想要正常运行的话，最好按照说明文档安装一下；然后这里的报错似乎是因为这个目录没有写入权限，放到桌面执行或许就没问题了。

**Comment by CareLaden** [comment]
我重新配置环境，完全没问题后测试，依旧存在一开始那个问题。那行代码注释掉后问题更多

**Comment by CareLaden** [comment]
我重新配置环境，测试后没啥大问题了。还是直接编译源代码好了，打包好的程序出现问题不方便修改。多谢解答哈哈

**Comment by liuhao326** [comment]
不用谢 ;-)

**Comment by CareLaden** [comment]
![image](https://user-images.githubusercontent.com/18063251/95169056-d99fd280-07e4-11eb-9390-67a9d16b538d.png)
这样舒服多了，直接保留着，免得哪天书籍下架或者微读越来越恶心就没法导出了。= =

**Comment by liuhao326** [comment]
嗯，是的。

**Comment by CareLaden** [comment]
这代码有两个还可以完善的地方。

- [ ] 除了现在现在所支持导出批注的功能，希望下一步能支持导出想法。

- [ ] 希望能提供自由选择导出哪些书籍。因为随着书籍数量越来越多，后面导出的耗费时间会越来越久。

**Comment by liuhao326** [comment]
嗯，是的，如果经常需要导出笔记及想法等内容，也可尝试使用插件 [wereader](https://github.com/liuhao326/wereader)。

**Comment by CareLaden** [comment]
可以，下次我试试，多谢推荐
